### ISSUE TITLE
Necessary csv files missing in the repo

### ISSUE THREAD

**Issue by pawel-kow** [CENTRprojects/Signs-of-life#3]
After overcoming #2 I faced the following error:
```
crawler-1     | Traceback (most recent call last):
crawler-1     |   File "app_domains/main_domains.py", line 20, in <module>
crawler-1     |     from classification_parked import predict_parking                       # DO_CONTENT_CLASSIFICATION
crawler-1     |   File "/signs-of-life/app_domains/classification_parked.py", line 87, in <module>
crawler-1     |     FT = Featurer(RUN_CONFIG) # features building
crawler-1     |   File "/signs-of-life/app_domains/ml/feature_eng.py", line 161, in __init__
crawler-1     |     DICO_TRANSLATION_BY_LGG, VOCABULARY, DICO_WORD_TYPES, DICO_WORD_TO_CLASS = get_reference_words(config)
crawler-1     |   File "/signs-of-life/app_domains/ml/feature_eng.py", line 48, in get_reference_words
crawler-1     |     df_trans = pd.read_csv(fp_trans, encoding="utf-8")
crawler-1     |   File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
crawler-1     |     return _read(filepath_or_buffer, kwds)
crawler-1     |   File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 448, in _read
crawler-1     |     parser = TextFileReader(fp_or_buf, **kwds)
crawler-1     |   File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 880, in __init__
crawler-1     |     self._make_engine(self.engine)
crawler-1     |   File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
crawler-1     |     self._engine = CParserWrapper(self.f, **self.options)
crawler-1     |   File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1874, in __init__
crawler-1     |     src = open(src, "rb")
crawler-1     | FileNotFoundError: [Errno 2] No such file or directory: '/signs-of-life/input/taxonomy.csv'
```

I think the issue is that `.gitignore` just removed all csv files from the repo, where some of them seem needed to run properly

**Comment by dm430as** [comment]
merged and fixed, thanks @pawel-kow
